# Generated by Django 5.2.6 on 2025-11-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('PE', 'Pets'), ('EL', 'Electronics'), ('TL', 'Tools'), ('VE', 'Vehicles'), ('BK', 'Books'), ('TO', 'Toys'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
